### REGISTER

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "email": "student3@gmail.com",
    "password": "Test@123",
    "role": "STUDENT"
}


### LOGIN

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "student2@gmail.com",
    "password": "Student@123"
}


### TEST WITHOUT JWT

GET http://localhost:8080/api/test


### TEST JWT

GET http://localhost:8080/api/test
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzg4NjEzOTY2LCJleHAiOjE3ODg2MTc1NjZ9.OP274-97RPW0DPu_mKqwFnVdS0lxseGBULk3QuztE_soVo7bGg32sMeeyTRz6pmC


### CREATE STUDENT PROFILE

POST http://localhost:8080/api/students/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzg4NjA4MjIwLCJleHAiOjE3ODg2MTE4MjB9.V6aRdqZe4vXgAo8d8Z2zdYBjSisltxUN3ZehhCe0MKwB0Kn7hre98ZNL03qowNN1

{
    "userId": 2,
    "name": "Subham",
    "education": "B.Tech",
    "branch": "Computer Science",
    "graduationYear": 2027
}


### GET STUDENT PROFILE

GET http://localhost:8080/api/students/profile
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzg4NjEzOTY2LCJleHAiOjE3ODg2MTc1NjZ9.OP274-97RPW0DPu_mKqwFnVdS0lxseGBULk3QuztE_soVo7bGg32sMeeyTRz6pmC


### Get my skills
GET http://localhost:8080/api/students/skills
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzg4NjEzOTY2LCJleHAiOjE3ODg2MTc1NjZ9.OP274-97RPW0DPu_mKqwFnVdS0lxseGBULk3QuztE_soVo7bGg32sMeeyTRz6pmC

### Add Java skill
POST http://localhost:8080/api/students/skills?skillId=1&level=BEGINNER&score=0
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzg4NjEzOTY2LCJleHAiOjE3ODg2MTc1NjZ9.OP274-97RPW0DPu_mKqwFnVdS0lxseGBULk3QuztE_soVo7bGg32sMeeyTRz6pmC
