spring.application.name=skillbridge-backend

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yezqtrtbutfvmpfyagmr
spring.datasource.password=8yTa*BjVgce5Cfu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true